WDSR: {n_feats: 128, n_resblocks: 16, res_scale: 1.0}
augment: true
batch_size: 16
data_dir: /input/train/
eval_dir: /input/eval/
test_dir: /input/test/
result_dir: /data/result/
hardware: {cuda: true, n_GPUs: 1, seed: 123, threads: 0}
log_dir: /output
lr: 0.001
model: WDSR
nEpochs: 150
only_eval: false
patch_size: 128
pre_train_path: ./weights//4x_WDSR_R16F64_9.pth
pre_trained: false
save_dir: ./weights/
scale: 4
snapshots: 5
startEpoch: 1
vFreq: 15
